# Even Fibonacci numbers: https://projecteuler.net/problem=2
# Problem 2 
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


def fibonacci(limit):
    a = 1
    b = 2
    while a < limit:
        yield a
        a, b = b, a + b

        
print sum(i for i in fibonacci(10000000) if i % 2 == 0)




